# Generated by Django 3.0.4 on 2020-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(blank=True, max_length=255, verbose_name='ISBN')),
                ('NDLBibID', models.CharField(max_length=255, verbose_name='NDL書誌ID')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('creator', models.CharField(blank=True, max_length=255, verbose_name='著者名')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版者')),
                ('date', models.CharField(max_length=255, verbose_name='出版年')),
                ('NDC', models.CharField(blank=True, max_length=255, verbose_name='NDC')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='件名')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='価格')),
                ('extent', models.CharField(blank=True, max_length=255, verbose_name='ページ数')),
            ],
        ),
    ]
