# Generated by Django 3.0.4 on 2020-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ASIN',
            field=models.CharField(blank=True, max_length=255, verbose_name='ASIN'),
        ),
    ]
