# Generated by Django 3.0.4 on 2020-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_book_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='注記'),
        ),
        migrations.AddField(
            model_name='book',
            name='publicationPlace',
            field=models.CharField(blank=True, max_length=255, verbose_name='出版地'),
        ),
        migrations.AddField(
            model_name='book',
            name='seriesTitle',
            field=models.CharField(default=1, max_length=255, verbose_name='シリーズ名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=255, verbose_name='巻次'),
        ),
    ]
