# Generated by Django 3.0.4 on 2020-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200422_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='partTC',
            field=models.CharField(blank=True, max_length=255, verbose_name='内容'),
        ),
    ]
