# Generated by Django 3.0.4 on 2020-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_book_parttc'),
    ]

    operations = [
        migrations.CreateModel(
            name='jpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(blank=True, max_length=255, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('volume', models.CharField(blank=True, max_length=255, verbose_name='巻次')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='副書名')),
                ('series', models.CharField(max_length=255, verbose_name='シリーズ名')),
                ('creator', models.CharField(blank=True, max_length=255, verbose_name='著者名')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版者')),
                ('date', models.CharField(max_length=255, verbose_name='出版日')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='価格')),
                ('extent', models.CharField(blank=True, max_length=255, verbose_name='ページ数')),
                ('ccode', models.CharField(blank=True, max_length=255, verbose_name='Cコード')),
                ('genrecode', models.CharField(blank=True, max_length=255, verbose_name='ジャンルコード')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='キーワード')),
                ('audience', models.CharField(blank=True, max_length=255, verbose_name='対象年齢')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='内容')),
                ('ToC', models.CharField(blank=True, max_length=255, verbose_name='目次')),
                ('datemodified', models.CharField(blank=True, max_length=255, verbose_name='データ修正日')),
            ],
        ),
    ]
