# Generated by Django 3.0.4 on 2020-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_jpro_creatornote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpro',
            name='NDC',
            field=models.CharField(blank=True, max_length=255, verbose_name='NDC'),
        ),
        migrations.AlterField(
            model_name='jpro',
            name='ToC',
            field=models.CharField(blank=True, max_length=1000, verbose_name='目次'),
        ),
        migrations.AlterField(
            model_name='jpro',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='jpro',
            name='series',
            field=models.CharField(blank=True, max_length=255, verbose_name='シリーズ名'),
        ),
    ]
